# JavaScript Reading Notes
- There are three languages that are used to create web pages:
  - ***HTML***
  - ***CSS***
  - ***JavaScript***
- HTML file will be linked to CSS and JavaScript files.
- Each langaue of them form a layout, but each layout building depends on the previous one.
- HTML forms a ***content layout***.
- CSS forms a ***presentation layout***.
- JavaScript forms a ***behavior layout***.
- **Progressive Enhancement:** the basis of a popular approach to building web pages that formed by the three layouts.
- ***HTML Only*** focuses on the content only.
- ***HTML+CSS*** focuses on the content and how it will be displayed.
- ***HTML+CSS+JAVASCRIPT*** enhances the usability of the page.
- **JavaScript File:** it is a text file that ends with ***.js***.
- The HTML (<"script">) element is used to load the JavaScript file into the page.   
- ***Source (src):*** path.
- **(document.write())** writes content into the document.
  - document : represents the entire of a web page.
  - (.) : it is a member operator.
  -  write(): it is a method with a parameter.
- ***Script:*** is a series of instructions that a computer can follow one-by-one. 
- ***Statement:***  individual instruction or step, follows by (;) and each one starts a new line.
- JavaScript is **Case Sensitive**.
- **Code Blocks:** statements that are surrounded by curly braces.
- **Comments** are used to explain what your code does. 
- Varibles (var as ***Keyword*** followed by the variable name): a place where you can temporarily store data.
- Data Types: 
  - Numeric: using variables to store numbers.
  - String: using variables to store texts.
  - Boolean: using variables to get true or false statment.
- Rules for naming variables:
  - The name must begin with a letter, dollar sign ($),or an underscore (_). It must not start with a number. 
  - The name can contain letters, numbers, dollar sign ($), or an underscore (_). Note that you must not use a dash(-) or a period (.) in a variable name.
  - You cannot use keywords or reserved words.
  - All variables are case sensitive.
  - Use a name that describes the kind of information that the variable stores.
  

